name: Publish Registry to ghcr.io

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  flutter:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ github.repository }} and push to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:sdk'
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            'FLUTTER_VERSION=3.13.5-stable'
          tags: | 
            ghcr.io/${{ github.repository_owner }}/flutter:stable