name: Publish Registry to ghcr.io

env:
  DOCKER_TAG: ghcr.io/arifai/flutter
  VERSION: 3.13.5

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  flutter:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }} Branch in ${{ github.repository }} Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ github.repository }} and push to ghcr.io
        run: |
          docker build -t $DOCKER_TAG:stable -t $DOCKER_TAG:$VERSION -t $DOCKER_TAG:latest --build-arg FLUTTER_VERSION=$VERSION-stable -f sdk/Dockerfile .
          docker push $DOCKER_TAG --all-tags